### ISSUE TITLE
This plugin was built for an outdated core ABI (39). Please rebuild the plugin with the latest API (81)

### ISSUE THREAD

**Issue by ren-zxcyq** [PistonMiner/binaryninja-bindiff-viewer#6]
Hello!

Not sure if it's just my env/binexport build, but I'm getting this error when running this Windows 10 on Binja 4.2.6455.

```c
[Default] Plugin module 'C:\Users\User\AppData\Roaming\Binary Ninja\plugins\binexport12_binaryninja.dll' failed to load
[Default] This plugin was built for an outdated core ABI (39). Please rebuild the plugin with the latest API (81).
```

**Comment by PistonMiner** [comment]
This is BinExport being outdated (possibly because a new Binary Ninja stable just came out and there's no new release build of BinExport against the new stable yet?). You'll need to rebuild it from source against the revision of the Binary Ninja API you are using.

While [this script](https://gist.github.com/psifertex/31d9bc3167eca91e466ebaae4382521c) is for Linux and Mac, the steps for swapping the revision I've found to work the same on Windows:
- find your revision in the `api_REVISION.txt` file with your Binary Ninja installation
- change the dev commit hash in `/cmake/BinExportDeps.cmake` to that revision
- run `regenerate-api-stubs.sh` against that revision of the API
- build as described in the BinExport instructions, adding the `-DBINEXPORT_BINARYNINJA_CHANNEL=DEV` option when configuring

The resulting DLL should load properly.

**Comment by ren-zxcyq** [comment]
Thank you very much for that!

I managed to build the DLL on Sunday, just didn't have much time to post my findings.
(It took a while - as I haven't built anything similar in the past from source - definitely hadn't used ninja / llvm)

I was able to run binexport from within binja but then wasn't able to see the UI differ window in it. -> UPDATE: After a clean restart of binja it works.

There are a couple of error messages in the log that seem related to the parsing, BUT overall exporting seems to be working.

![image](https://github.com/user-attachments/assets/14eb0467-ab28-438a-82ce-9ae44f14fc15)

![image](https://github.com/user-attachments/assets/36e171ac-e1e8-4e70-8dce-dce316d64807)

in bindiff
![image](https://github.com/user-attachments/assets/0a0e44d5-fc3c-4157-bb70-688ef8fbf6c1)

![image](https://github.com/user-attachments/assets/ed741cda-2ff4-44ca-a15c-139e83c66814)

and back in BinDiff Viewer:
![image](https://github.com/user-attachments/assets/6341d1f8-b57b-41e0-b193-d9bd0beb0324)


Thank you for this!
